db:
  url: jdbc:mysql://localhost:3306/mydb
  username: root
  password: tjee1234

file:
  upload:
    profile-path: C:/uploads/profile
    board-path: C:/uploads/board

mail:
  username: minyung0723@gmail.com  # email
  password: qifa rzwt cmtz rfoj     # password app password 16자리로 이루어짐 2차 비밀번호 인증 통해 발급

jwt:
  config:
    secret: springboard-jwt-secret-key-2026-change-this-please!!